#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Chat.Android.Resource", IsApplication=true)]

namespace Chat.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::blocke.circleimageview.Resource.Attribute.civ_border_color = global::Chat.Android.Resource.Attribute.civ_border_color;
			global::blocke.circleimageview.Resource.Attribute.civ_border_overlay = global::Chat.Android.Resource.Attribute.civ_border_overlay;
			global::blocke.circleimageview.Resource.Attribute.civ_border_width = global::Chat.Android.Resource.Attribute.civ_border_width;
			global::blocke.circleimageview.Resource.Attribute.civ_fill_color = global::Chat.Android.Resource.Attribute.civ_fill_color;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView = global::Chat.Android.Resource.Styleable.CircleImageView;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_border_color = global::Chat.Android.Resource.Styleable.CircleImageView_civ_border_color;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_border_overlay = global::Chat.Android.Resource.Styleable.CircleImageView_civ_border_overlay;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_border_width = global::Chat.Android.Resource.Styleable.CircleImageView_civ_border_width;
			global::blocke.circleimageview.Resource.Styleable.CircleImageView_civ_fill_color = global::Chat.Android.Resource.Styleable.CircleImageView_civ_fill_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int civ_border_color = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int civ_border_overlay = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int civ_border_width = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int civ_fill_color = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int btnCahngeLng = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int btnFind = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int btnSignIn = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnSignUp = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int collectionView = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int editFind = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int editLogin = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int editPass = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int imageCard = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int textCard = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int textError = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int txtLng = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int txtLogin = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int txtPass = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NewsCard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Registration = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
